select * from cirurgia.pergunta_cirurgia;
-- PERGUNTAS
-- Momento 1
-- Paramêtros(id_pergunta, tx_pergunta, tx_tipo_pergunta,in_teclado_numerico, bl_notificar)
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar)  VALUES ('A010-000', 'Gênero do profissional notificante:','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A020-000', 'Nome do Paciente:','SUB',1, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A030-000', 'Endereço:', 'SUB',1, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A040-000', 'Telefone:','SUB',2, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A050-000', 'Data de nascimento: ','SUB',3, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A060-000', 'Sexo do paciente:', 'OBJ', 0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A070-000', 'Situação conjugal:', 'OBJ', 0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A080-000', 'Autorizou a cirurgia mediante assinatura de documento?','OBJ', 0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A090-000', 'Data da cirurgia:', 'SUB', 3, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A100-000', 'Nome do acompanhante:','SUB',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A110-000', 'Nome do médico cirurgião:','SUB',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A120-000', 'Nome do enfermeiro responsável:', 'SUB', 0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A130-000', 'Realizam controle do Índice Glicêmico às 6h da manhã do dia da cirurgia? (Menor que 200 mg/dl)?', 'OBJ', 0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A140-000', 'Realizam tricotomia com tricotomizador elétrico, imediatamente antes da cirurgia e na menor área possível?','OBJ', 0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A150-000', 'O sítio cirúrgico foi demarcado?','OBJ',0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A160-000', 'O oxímetro de pulso está funcionante?', 'OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A170-000', 'O paciente está monitorizado com oxímetro de pulso?', 'OBJ', 0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A180-000', 'Apresenta risco de reação alérgica ou restrição a medicamento, verbalizado ou conferido no prontuário?','OBJ',0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A190-000', 'Apresenta risco de perda sanguínea > 500 ml em adultos e em crianças 7 ml/kg?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A190-010', 'O paciente possui 2 acessos calibrosos/ ou 01 acesso central e fluidos previstos?', 'OBJ',0,FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A190-020', 'Possui reservas de fluidos e sangue?', 'OBJ',0,FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A200-000', 'Apresenta risco de via aérea difícil/ broncoaspiração:(escala de Mallampati: classe III e IV difíceis) :','OBJ',0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A200-010', 'Ainda se positivo, o profissional fez provisão de material/equipamento específicos?', 'OBJ',0,FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A210-000', 'Apresenta risco de broncoaspiração?','OBJ',0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A210-010', 'Ainda se positivo, o profissional fez provisão de material/equipamento específicos?', 'OBJ',0,FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('A220-000', 'Realizada verificação de segurança anestésica?(Conjunto de ações realizadas pelo anestesiologista, que envolvem a inspeção formal do equipamento, checagem dos medicamentos e do risco anestésico do paciente antes da realização de cada cirurgia).', 'OBJ',0,TRUE);
-- Momento 2
-- Paramêtros(id_pergunta, tx_pergunta, tx_tipo_pergunta,in_teclado_numerico, bl_notificar)
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B010-000', 'Todos os membros se apresentam pelo nome e função?', 'OBJ', 0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B020-000', 'Todos os membros da equipe confirmaram verbalmente identificação do paciente?', 'OBJ', 0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B030-000', 'Todos os membros da equipe confirmaram verbalmente o sítio cirúrgico?','OBJ', 0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B040-000', 'Todos os membros da equipe confirmaram verbalmente o procedimento a ser realizado?', 'OBJ',0,TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B050-000', 'O cirurgião realizou a previsão de eventos críticos e inesperados?\n A exemplo: de duração da operação estimada, de perda sanguínea (superior a 500 ml para adultos e 7 ml/kg em crianças)','OBJ',0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B060-000', 'O anestesiologista realizou a revisão da existência de etapas críticas ou inesperadas (via área difícil)','OBJ',0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B070-000', 'Com relação à revisão dos materiais necessários realizada pela equipe de enfermagem, nas etapas críticas ou inesperadas, a exemplo de esterilidade dos materiais ou algum problema com relação aos equipamentos. Responda as questões a seguir:','NUL',0, FALSE); --ESSE DAQUI NAO EH UMA PERGUNTA
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B070-010', 'Os instrumentais cirúrgicos estão presentes e dentro do prazo de validade:','OBJ',0,FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B070-020', 'As próteses estão presentes e dentro do prazo de validade?', 'OBJ',0,FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B070-030', 'Os indicadores químicos estavam presentes nos pacotes cirúrgicos?', 'OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B080-000', 'Todos os artigos que serão utilizados estão presentes na Sala de Operação e dentro do prazo de validade da esterilização?','OBJ',0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B090-000', 'Os indicadores químicos do processo de esterilização foram avalizados quanto a presença, reação positiva e validade nos pacotes cirúrgicos?','OBJ',0, TRUE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B100-000', 'Há algum problema, fragilidade ou preocupação identificada relacionada à equipamentos que serão utilizados na cirurgia?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B100-010', 'Caso positivo, foram tomadas medidas?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B110-000', 'Foi realizada profilaxia antimicrobiana nos últimos 60 minutos?\n (Indicação: cirurgias contaminadas; potencialmente contaminadas; limpas de grande porte; com implante de prótese; de emergência e nas realizadas em pacientes de maior risco)','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B120-000', 'Os exames de imagem estão disponíveis na sala operatória?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B130-000', 'Foram checados os matérias que serão utilizados na cirurgia por parte da equipe de enfermagem?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B140-000', 'No caso de hipotermia, usaram a temperatura de 36,5°C como ponto de corte para iniciar as intervenções para controlar a hipotermia do INTRA-OPERATÓRIO?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B150-000', 'Realizam controle da temperatura ambiental da sala de operação?\n (Recomendação: entre 18°C a 24°C)', 'OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B160-000', 'As portas das salas de operação são mantidas fechadas durante o ato operátorio?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('B170-000', 'O número de pessoas nas salas de operação durante a cirurgia é limitado?\n (Máximo de 06 pessoas)','OBJ',0, FALSE);
-- Momento 3
-- Paramêtros(id_pergunta, tx_pergunta, tx_tipo_pergunta,in_teclado_numerico, bl_notificar)
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUEs ('C010-000', 'Foi realizado o registro completo do procedimento intra-operatório, incluindo procedimento executado?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C020-000', 'Foi realizada a contagem de instrumentais cirúrgicos?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C030-000', 'Foi realizada a contagem de compressas cirúrgicas?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C040-000', 'Foi realizada a contagem de Agulhas?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C050-000', 'Os espécimes cirúrgicos (amostras) a serem encaminhados para anatomia patológica, foram identificados com todas as informações obrigatórias?\n(Nome do paciente, data de nascimento do paciente, pedido do médico, nome do médico, registro na instituição, data, rubrica do profissional que fez a identificação, número COREN, identificação da peça e conferência das informações da amostra','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C060-000', 'Há algum problema com equipamento para ser resolvido?', 'OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C070-000', 'O cirurgião revisa preocupações essenciais para a recuperação e o manejo do paciente?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C080-000', 'O anestesiologista revisa preocupações essenciais para a recuperação e o manejo do paciente?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C090-000', 'A equipe de enfermagem revisa preocupações essenciais para a recuperação e o manejo do paciente?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C100-000', 'Realizam controle da temperatura corporal?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C110-000', 'Realizam controle da saturação de oxigênio?\n(Igual ou superior a 95%)','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C120-000', 'Realizam controle da Frequência Cardíaca?','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C130-000', 'Realizam controle da Pressão Arterial? (PAM > que 60 mmHg e < que 110 mmHg)','OBJ',0, FALSE);
INSERT INTO cirurgia.pergunta_cirurgia (id_pergunta, tx_pergunta, tx_tipo_pergunta, in_teclado_numerico, bl_notificar) VALUES ('C140-000', 'Realizam o controle da dor pós-operatória?','OBJ',0, FALSE);
